<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenSuiteDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>add81500-5974-452e-b17a-d2dab491b7db</testSuiteGuid>
   <testCaseLink>
      <guid>1667c434-4435-434d-910d-688c3e06dfa3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>3fbc9cd5-0a6b-46cd-930b-15e883fdec1d</id>
         <masked>false</masked>
         <name>password</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Demo/DataDrivenTesting</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f4a319be-c168-4bd3-b072-72d321ea0604</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f4a319be-c168-4bd3-b072-72d321ea0604</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>3eeae993-d91b-45f5-9bca-25fe80132f96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f4a319be-c168-4bd3-b072-72d321ea0604</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>3fbc9cd5-0a6b-46cd-930b-15e883fdec1d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
