<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Paragraph_mce_0_ifr</name>
   <tag></tag>
   <elementGuidId>6734cbfe-ce39-4ea4-84cb-ca043436a5d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mce_0_ifr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mce_0_ifr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>def9e869-f2d4-46dc-a2d3-30c0d510c6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mce_0_ifr</value>
      <webElementGuid>9b57db62-3a68-4ed1-89b1-5e943a4caa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e9b7b065-1a7f-4205-bbd6-fa7973764495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fc3211fc-7279-4fa0-bdc4-8a61b93444a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area</value>
      <webElementGuid>3d6eb945-20c7-4e6d-9e48-6c3af3eed4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tox-edit-area__iframe</value>
      <webElementGuid>920afb87-af0c-42d9-991f-3bc5c74dfe65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mce_0_ifr&quot;)</value>
      <webElementGuid>41c98270-8aa2-4ecb-a29d-9e223cae5249</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mce_0_ifr']</value>
      <webElementGuid>8bd9d1cf-ae1f-433c-9667-48e417a866cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div[2]/div/iframe</value>
      <webElementGuid>65e2273b-01d2-4c2a-9c60-41ad4341c197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d0ac40f7-77c3-434f-ab7f-a8c672700157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mce_0_ifr' and @title = 'Rich Text Area']</value>
      <webElementGuid>eb4cad2b-d72c-443e-8b6a-6386af6e9c5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
